import { BRIT_DATA } from "@/lib/data";

let qaIndex: ReturnType<typeof buildKnowledgeBase> | null = null;

const STOP = new Set([
  "the", "and", "for", "are", "but", "not", "you", "all", "can", "has", "was", "one", "our", "out",
  "what", "how", "why", "when", "who", "which", "about", "from", "with", "tell", "give", "show", "me", "any", "does", "did",
]);

const tokenize = (q: string) =>
  (q || "")
    .toLowerCase()
    .replace(/[^a-z0-9\s%/]/g, " ")
    .split(/\s+/)
    .filter((w) => w.length > 1 && !STOP.has(w));

const buildKnowledgeBase = () => {
  const D = BRIT_DATA;
  if (!D) return [];
  const entries: {
    keywords: string[];
    title: string;
    body: string;
    bullets: string[];
    source: string;
    blob: string;
  }[] = [];

  const add = (keywords: string[], title: string, body: string, bullets: string[], source: string) => {
    entries.push({
      keywords: keywords.map((k) => k.toLowerCase()),
      title,
      body,
      bullets: bullets || [],
      source: source || "Flavor Insights India · 20 May 2026",
      blob: [title, body, ...(bullets || []), ...keywords].join(" ").toLowerCase(),
    });
  };

  const m = D.meta;
  add(
    ["summary", "overview", "report", "dataset", "flavor insights", "full", "everything", "breakdown"],
    "Full dataset overview",
    D.breakdown?.overview ||
      `${m.title}: ${m.totalSample.toLocaleString("en-IN")} conversations across ${m.channels.join(", ")} in ${m.country} over the ${m.period}.`,
    D.breakdown?.sections?.flatMap((s) => [`${s.title}: ${s.bullets[0]}`]) || [],
    `${m.generatedBy} · ${m.date}`
  );

  add(
    ["methodology", "method", "sample", "channels", "conversations", "data source", "how many", "sample size"],
    "Methodology & sample",
    `Analysis on ${m.totalSample.toLocaleString("en-IN")} conversations on ${m.channels.join(", ")} in India over the ${m.period}. Generated by ${m.generatedBy} in ${m.generationTime}.`,
    m.channels.map((c) => `Channel: ${c}`),
    "Report methodology"
  );

  const hc = D.honeyChilli;
  add(
    ["honey chilli", "honey chili", "sweet heat", "sweet-heat", "swicy"],
    hc.headline,
    `${hc.narrative} ${hc.convGrowthPct}% conversation growth, ${hc.engGrowthPct}% engagement growth.`,
    [`Trend: ${hc.trendType}`, `Extensions: ${hc.extensions.join(", ")}`],
    "Honey Chilli · national matrix"
  );

  const gp = D.gunpowderPodi;
  add(
    ["gunpowder", "podi", "milagai", "south indian", "chennai", "bangalore"],
    gp.headline,
    `${gp.narrative} ${gp.convGrowthPct}% conversation growth, ${gp.engGrowthPct}% engagement growth.`,
    [`Trend: ${gp.trendType}`, `Extensions: ${gp.extensions.join(", ")}`],
    "Gunpowder Podi · South India"
  );

  add(
    ["schezwan", "chaat masala", "tandoori", "favorite savory", "savory shares", "snack flavor"],
    "Top savory flavors (India)",
    "Honey Chilli and Gunpowder Podi lead national growth. Schezwan Masala and Chaat Masala Blast dominate North urban snacking.",
    (D.favoriteSavoryShares || []).map((f) => `${f.flavor}: momentum index ${f.pct}`),
    "National prioritization"
  );

  const rs = D.regionalSweetSentiment;
  add(
    ["sentiment", "positive", "negative", "neutral", "mishti", "nolen", "regional sweet"],
    rs.headline,
    `${rs.narrative} ${rs.positivePct}% positive across regional sweet conversations.`,
    [
      `Sentiment: ${rs.sentiment.positive}% positive, ${rs.sentiment.neutral}% neutral, ${rs.sentiment.negative}% negative`,
    ],
    "Regional sweets sentiment"
  );

  D.states?.forEach((row) => {
    const keys = [row.state.toLowerCase(), ...(row.aliases || [])];
    add(
      keys.concat(["state", "region", "flavors", "flavours", "top flavors"]),
      `Top flavors — ${row.state}`,
      `${row.state} sweet top 5: ${row.sweet.join(", ")}. Savory top 5: ${row.savory.join(", ")}.`,
      [`Sweet: ${row.sweet.join(" · ")}`, `Savory: ${row.savory.join(" · ")}`],
      "State flavor table"
    );
  });

  D.sweetOpportunities?.forEach((o) => {
    add(
      [o.flavor.toLowerCase(), "sweet", "opportunity", "extension", ...(o.anchor || "").toLowerCase().split(/[,\s]+/)],
      `Sweet opportunity — ${o.flavor}`,
      `${o.proof} Regional anchor: ${o.anchor}.`,
      [
        `Extensions: ${o.extensions.join(", ")}`,
        ...Object.entries(o.metrics || {}).map(([k, v]) => `${k}: ${v}%`),
      ],
      `Sweet opportunities · ${o.flavor}`
    );
  });

  D.savoryOpportunities?.forEach((o) => {
    add(
      [o.flavor.toLowerCase(), "savory", "savoury", "namkeen", "snack", ...(o.anchor || "").toLowerCase().split(/[,\s]+/)],
      `Savory opportunity — ${o.flavor}`,
      `${o.proof} Regional anchor: ${o.anchor}.`,
      [
        `Extensions: ${o.extensions.join(", ")}`,
        ...Object.entries(o.metrics || {}).map(([k, v]) => `${k}: ${v}%`),
      ],
      `Savory opportunities · ${o.flavor}`
    );
  });

  add(
    ["extension", "extensions", "launch", "product ideas", "opportunities"],
    "All extension opportunities",
    "Indian sweet and savory extension ideas from the national matrix and state tables — Honey Chilli, Gunpowder Podi, and regional platforms.",
    [
      `Honey Chilli: ${hc.extensions.join(", ")}`,
      `Gunpowder Podi: ${gp.extensions.join(", ")}`,
      ...D.sweetOpportunities.flatMap((o) => o.extensions.slice(0, 2).map((e) => `${o.flavor}: ${e}`)),
      ...D.savoryOpportunities.flatMap((o) => o.extensions.slice(0, 2).map((e) => `${o.flavor}: ${e}`)),
    ],
    "Extension lists"
  );

  add(
    ["compare", "versus", "vs", "stronger", "better", "which", "prioritize"],
    "Honey Chilli vs Gunpowder Podi",
    `Honey Chilli (${hc.convGrowthPct}% conv. growth) is the national sweet-heat bet. Gunpowder Podi (${gp.convGrowthPct}% conv. growth) is the South savory anchor. Launch Honey Chilli nationally; podi formats in TN, Karnataka, AP, Telangana.`,
    ["Honey Chilli: pan-India coated crackers, chips, biscuits", "Gunpowder Podi: podi crackers, khakhra, savory biscuits"],
    "Comparative read"
  );

  add(
    ["thecha", "bhakarwadi", "sattu", "kasundi", "mishti", "tamarind"],
    "Regional flavor deep-dive",
    "Key regional platforms from state tables and opportunity lists.",
    [...D.savoryOpportunities, ...D.sweetOpportunities].map((o) => `${o.flavor}: ${o.proof.slice(0, 80)}…`),
    "Regional opportunities"
  );

  return entries;
};

const scoreEntry = (tokens: string[], entry: (typeof qaIndex)[0]) => {
  let s = 0;
  const blob = entry.blob;
  tokens.forEach((t) => {
    if (blob.includes(t)) s += t.length > 5 ? 4 : 2;
    entry.keywords.forEach((k) => {
      if (k.includes(t) || t.includes(k)) s += 5;
    });
  });
  return s;
};

export const answerQuestion = (query: string) => {
  const index = qaIndex ?? (qaIndex = buildKnowledgeBase());
  const tokens = tokenize(query);
  if (!tokens.length) {
    return {
      title: "Flavor Insights India",
      body: BRIT_DATA?.breakdown?.overview,
      bullets: ["Ask about any state, Honey Chilli, Gunpowder Podi, extensions, or regional sweets."],
      sources: ["Consuma AI · 20 May 2026"],
      related: (BRIT_DATA?.predefinedQuestions || []).slice(0, 4).map((p) => p.q),
    };
  }

  const ranked = index
    .map((e) => ({ e, s: scoreEntry(tokens, e) }))
    .filter((x) => x.s > 0)
    .sort((a, b) => b.s - a.s);

  if (!ranked.length) {
    return {
      title: "Not in this dataset",
      body: "That topic isn't directly tagged in Flavor Insights India. The report covers 29 state flavor maps, Honey Chilli, Gunpowder Podi, regional sweets, and Indian extension ideas.",
      bullets: (BRIT_DATA?.predefinedQuestions || []).map((p) => p.q),
      sources: [`1,53,496 conversations · ${BRIT_DATA.meta?.channels?.length || 9} channels`],
      related: [],
    };
  }

  const top = ranked.slice(0, 3).map((x) => x.e);
  const primary = top[0];
  const extraBullets = top.slice(1).flatMap((e) => e.bullets.slice(0, 2));
  const allBullets = [...primary.bullets, ...extraBullets].slice(0, 10);

  return {
    title: primary.title,
    body: primary.body,
    bullets: allBullets.length ? allBullets : undefined,
    sources: [...new Set(top.map((e) => e.source))],
    related: suggestRelated(query, primary),
  };
};

const suggestRelated = (query: string, primary: { title: string }) => {
  const ql = query.toLowerCase();
  const out: string[] = [];
  const presets = BRIT_DATA?.predefinedQuestions || [];
  presets.forEach((p) => {
    if (!ql.includes(p.id) && p.q !== query) out.push(p.q);
  });
  if (primary.title.includes("Honey")) out.push("Gunpowder Podi savory opportunity");
  if (primary.title.includes("Gunpowder")) out.push("Honey Chilli trends and extensions");
  if (primary.title.includes("state")) out.push("What are all extension opportunities?");
  return out.slice(0, 4);
};

export const wantsFullResearch = (query: string) => {
  const presets = BRIT_DATA?.predefinedQuestions || [];
  const ql = (query || "").toLowerCase().trim();
  const researchPresets = presets.filter((p) => p.research);
  const hit = researchPresets.find((p) => {
    const pq = p.q.toLowerCase();
    return ql === pq || ql.includes(pq.slice(0, 20)) || pq.includes(ql.slice(0, 20));
  });
  if (hit) return true;
  const pipelinePhrases = [
    "top flavour trends by state",
    "top flavor trends by state",
    "map india",
    "traditional sweet and savory",
    "sentiment towards regional sweets",
    "all extension opportunities",
    "honey chilli",
    "gunpowder podi",
  ];
  return pipelinePhrases.some((ph) => ql.includes(ph.slice(0, 24)));
};

export const getDatasetSummary = () => {
  const D = BRIT_DATA;
  return {
    title: D?.meta?.title || "Flavor Insights India",
    overview: D?.breakdown?.overview,
    sections: D?.breakdown?.sections || [],
  };
};
