import { BRIT_DATA } from "@/lib/data";

let qaIndex: ReturnType<typeof buildKnowledgeBase> | null = null;

  const STOP = new Set(["the","and","for","are","but","not","you","all","can","has","was","one","our","out","what","how","why","when","who","which","about","from","with","tell","give","show","me","any","does","did"]);

  const tokenize = (q) =>
    (q || "").toLowerCase()
      .replace(/[^a-z0-9\s%/]/g, " ")
      .split(/\s+/)
      .filter((w) => w.length > 1 && !STOP.has(w));

  const buildKnowledgeBase = () => {
    const D = BRIT_DATA;
    if (!D) return [];
    const entries = [];
    const add = (keywords, title, body, bullets, source) => {
      entries.push({
        keywords: keywords.map((k) => k.toLowerCase()),
        title,
        body,
        bullets: bullets || [],
        source: source || "Flavor Insights India · 20 May 2026",
        blob: [title, body, ...(bullets || []), ...keywords].join(" ").toLowerCase(),
      });
    };

    const m = D.meta;
    add(
      ["summary", "overview", "report", "dataset", "flavor insights", "full", "everything", "breakdown"],
      "Full dataset overview",
      D.breakdown?.overview || `${m.title}: ${m.totalSample.toLocaleString("en-IN")} conversations across ${m.channels.join(", ")} in ${m.country} over the ${m.period}.`,
      D.breakdown?.sections?.flatMap((s) => [`${s.title}: ${s.bullets[0]}`]) || [],
      `${m.generatedBy} · ${m.date}`
    );

    add(
      ["methodology", "method", "sample", "channels", "conversations", "data source", "how many", "sample size"],
      "Methodology & sample",
      `Analysis on ${m.totalSample.toLocaleString("en-IN")} conversations on ${m.channels.join(", ")} in India over the ${m.period}. Generated by ${m.generatedBy} in ${m.generationTime}.`,
      m.channels.map((c) => `Channel: ${c}`),
      "Report methodology"
    );

    const b = D.biscoff;
    add(
      ["biscoff", "lotus", "speculoos", "dessert biscuit", "biscuit sentiment", "biscuits sweets"],
      b.headline,
      `${b.strategy} ${b.positivePct}% positive sentiment across ${b.conversations.toLocaleString("en-IN")} conversations. ${b.whyItWins}`,
      [
        `Sentiment in sweets: ${b.sentiment.positive}% positive, ${b.sentiment.neutral}% neutral, ${b.sentiment.negative}% negative`,
        `Headline positive sentiment: ${b.positivePct}%`,
        `Extensions: ${b.extensions.join(", ")}`,
      ],
      `${b.conversations.toLocaleString("en-IN")} Biscoff conversations`
    );

    const hc = D.honeyChilli;
    add(
      ["peri peri", "periperi", "favorite savory", "savory shares", "snack flavor ranking", "menu share"],
      "Favorite savory flavor shares (India)",
      "Peri Peri leads favorite snack-menu conversations at 22%. Honey Chilli is second at 18%.",
      D.favoriteSavoryShares.map((f) => `${f.flavor}: ${f.pct}%`),
      "Favorite flavor shares · report p.3"
    );

    add(
      ["honey chilli", "honey chili", "swicy", "spicy", "hot honey", "global spice", "favorite flavor", "favourite flavor", "savory share", "snack menu"],
      hc.headline,
      `${hc.narrative} ${hc.favShareNote}`,
      [
        `${hc.conversations.toLocaleString("en-IN")} Honey Chilli conversations`,
        `${hc.globalSpiceInterest}% global-spice interest`,
        `${hc.savoryInnovationDemand}% savory innovation demand`,
        `${hc.fusionFlavourEnthusiasm}% fusion flavour enthusiasm`,
        `Extensions: ${hc.extensions.join(", ")}`,
        ...D.favoriteSavoryShares.map((f) => `${f.flavor}: ${f.pct}% favorite share`),
      ],
      "Honey Chilli · report p.2–3"
    );

    D.states?.forEach((row) => {
      const keys = [row.state.toLowerCase(), ...(row.aliases || [])];
      add(
        keys.concat(["state", "region", "flavors", "flavours", "top flavors"]),
        `Top flavors — ${row.state}`,
        `${row.state} sweet top 5: ${row.sweet.join(", ")}. Savory top 5: ${row.savory.join(", ")}.`,
        [`Sweet: ${row.sweet.join(" · ")}`, `Savory: ${row.savory.join(" · ")}`],
        "State flavor table · report p.3–4"
      );
    });

    D.sweetOpportunities?.forEach((o) => {
      add(
        [o.flavor.toLowerCase(), "sweet", "opportunity", "extension", ...(o.anchor || "").toLowerCase().split(/[,\s]+/)],
        `Sweet opportunity — ${o.flavor}`,
        `${o.proof} Regional anchor: ${o.anchor}.`,
        [`Extensions: ${o.extensions.join(", ")}`, Object.entries(o.metrics || {}).map(([k, v]) => `${k}: ${v}%`).join(" · ")],
        `Sweet opportunities · ${o.flavor}`
      );
    });

    D.savoryOpportunities?.forEach((o) => {
      add(
        [o.flavor.toLowerCase(), "savory", "savoury", "namkeen", "snack", ...(o.anchor || "").toLowerCase().split(/[,\s]+/)],
        `Savory opportunity — ${o.flavor}`,
        `${o.proof} Regional anchor: ${o.anchor}.`,
        [`Extensions: ${o.extensions.join(", ")}`, Object.entries(o.metrics || {}).map(([k, v]) => `${k}: ${v}%`).join(" · ")],
        `Savory opportunities · ${o.flavor}`
      );
    });

    add(
      ["extension", "extensions", "sku", "launch", "product ideas", "opportunities"],
      "All extension opportunities",
      "From the report — Biscoff dessert extensions plus Honey Chilli swicy formats plus flavor-platform SKUs.",
      [
        `Biscoff (${b.extensions.length}): ${b.extensions.join(", ")}`,
        `Honey Chilli (${hc.extensions.length}): ${hc.extensions.join(", ")}`,
        ...D.sweetOpportunities.flatMap((o) => o.extensions.slice(0, 2).map((e) => `${o.flavor}: ${e}`)),
        ...D.savoryOpportunities.flatMap((o) => o.extensions.slice(0, 2).map((e) => `${o.flavor}: ${e}`)),
      ],
      "Extension lists · report"
    );

    add(
      ["sentiment", "positive", "negative", "neutral", "feeling", "perception"],
      "Sentiment — Biscoff in sweets",
      `Biscoff sentiment towards sweets: ${b.sentiment.positive}% positive, ${b.sentiment.neutral}% neutral, ${b.sentiment.negative}% negative. Headline positive: ${b.positivePct}%.`,
      [`Based on ${b.conversations.toLocaleString("en-IN")} Biscoff conversations`],
      "Sentiment chart · report p.2"
    );

    add(
      ["compare", "versus", "vs", "stronger", "better", "which"],
      "Biscoff vs Honey Chilli",
      `Different bets: Biscoff = premium dessert trust (${b.positivePct}% positive, ${b.conversations.toLocaleString("en-IN")} convos). Honey Chilli = swicy snack momentum (${hc.favSharePct}%+ favorite snack share, ${hc.conversations.toLocaleString("en-IN")} convos, Peri Peri still #1 at 22%).`,
      ["Biscoff: dessert system, transparency, imitation risk", "Honey Chilli: chips, makhana, global spice 55%"],
      "Comparative read · report"
    );

    add(
      ["premium", "pricing", "luxury", "health", "natural", "protein", "gifting", "diwali", "holi"],
      "Premium & health signals (sweet flavors)",
      "Strongest pricing/power signals from sweet opportunity metrics in the report.",
      D.sweetOpportunities.map((o) => {
        const met = Object.entries(o.metrics || {}).map(([k, v]) => `${k} ${v}%`).join(", ");
        return `${o.flavor} (${o.anchor}): ${met || o.proof.slice(0, 60)}`;
      }),
      "Sweet opportunity metrics"
    );

    add(
      ["thecha", "bhakarwadi", "sattu", "gunpowder", "podi", "milagai", "masala"],
      "Savory flavor deep-dive",
      "Key savory platforms from the report with spice/fusion/protein angles.",
      D.savoryOpportunities.map((o) => `${o.flavor}: ${o.proof}`),
      "Savory opportunities"
    );

    return entries;
  };

  const scoreEntry = (tokens, entry) => {
    let s = 0;
    const blob = entry.blob;
    tokens.forEach((t) => {
      if (blob.includes(t)) s += t.length > 5 ? 4 : 2;
      entry.keywords.forEach((k) => {
        if (k.includes(t) || t.includes(k)) s += 5;
      });
    });
    return s;
  };

  const answerQuestion = (query) => {
    const index = qaIndex ?? (qaIndex = buildKnowledgeBase());
    const tokens = tokenize(query);
    if (!tokens.length) {
      return {
        title: "Flavor Insights India",
        body: BRIT_DATA?.breakdown?.overview,
        bullets: ["Ask about any state, flavor, Biscoff, Honey Chilli, extensions, or sentiment."],
        sources: ["Consuma AI · 20 May 2026"],
        related: (BRIT_DATA?.predefinedQuestions || []).slice(0, 4).map((p) => p.q),
      };
    }

    const ranked = index
      .map((e) => ({ e, s: scoreEntry(tokens, e) }))
      .filter((x) => x.s > 0)
      .sort((a, b) => b.s - a.s);

    if (!ranked.length) {
      return {
        title: "Not in this dataset",
        body: "That topic isn't directly tagged in Flavor Insights India. The report covers Biscoff, Honey Chilli, 11 state flavor maps, favorite savory shares, and 10 sweet/savory opportunity platforms.",
        bullets: (BRIT_DATA?.predefinedQuestions || []).map((p) => p.q),
        sources: ["1,53,496 conversations · 6 channels"],
        related: [],
      };
    }

    const top = ranked.slice(0, 3).map((x) => x.e);
    const primary = top[0];
    const extraBullets = top.slice(1).flatMap((e) => e.bullets.slice(0, 2));
    const allBullets = [...primary.bullets, ...extraBullets].slice(0, 10);

    return {
      title: primary.title,
      body: primary.body,
      bullets: allBullets.length ? allBullets : undefined,
      sources: [...new Set(top.map((e) => e.source))],
      related: suggestRelated(query, primary),
    };
  };

  const suggestRelated = (query, primary) => {
    const ql = query.toLowerCase();
    const out = [];
    const presets = BRIT_DATA?.predefinedQuestions || [];
    presets.forEach((p) => {
      if (!ql.includes(p.id) && p.q !== query) out.push(p.q);
    });
    if (primary.title.includes("Biscoff")) out.push("Honey Chilli and favorite savory flavor shares");
    if (primary.title.includes("Honey")) out.push("Tell me everything about Biscoff");
    if (primary.title.includes("state")) out.push("What are all extension opportunities?");
    return out.slice(0, 4);
  };

  const wantsFullResearch = (query) => {
    const presets = BRIT_DATA?.predefinedQuestions || [];
    const ql = (query || "").toLowerCase().trim();
    const researchPresets = presets.filter((p) => p.research);
    const hit = researchPresets.find((p) => {
      const pq = p.q.toLowerCase();
      return ql === pq || ql.includes(pq.slice(0, 20)) || pq.includes(ql.slice(0, 20));
    });
    if (hit) return true;
    const pipelinePhrases = [
      "top flavour trends by state",
      "top flavor trends by state",
      "sentiment towards biscuits and sweets",
      "all extension opportunities",
      "honey chilli and favorite savory",
    ];
    return pipelinePhrases.some((ph) => ql.includes(ph.slice(0, 24)));
  };

  const getDatasetSummary = () => {
    const D = BRIT_DATA;
    return {
      title: D.meta.title,
      date: D.meta.date,
      overview: D.breakdown.overview,
      sections: D.breakdown.sections,
    };
  };

  const isInstantOnlyQuestion = (query) => {
    const presets = BRIT_DATA?.predefinedQuestions || [];
    const ql = (query || "").toLowerCase().trim();
    return presets.some(
      (p) =>
        p.research === false &&
        (ql === p.q.toLowerCase() || ql.includes(p.id) || p.q.toLowerCase().includes(ql.slice(0, 20)))
    );
  };


export { answerQuestion, buildKnowledgeBase, wantsFullResearch, isInstantOnlyQuestion, getDatasetSummary, tokenize };
